// JSXTRANSFORMER_SETUP:{"root":"pathindex","dirs":["metadatas"]}
// DO NOT EDIT THIS FILE
// THIS FILE WAS GENERATED AUTOMATICALLY BY JSXTRANSFORMER

if (!pathindex.metadatas){pathindex.metadatas = {};}
