// JSXTRANSFORMER_SETUP:{"root":"async","dirs":["jobs","navigate","pagination","pathindex","search","watchfolders"]}
// DO NOT EDIT THIS FILE
// THIS FILE WAS GENERATED AUTOMATICALLY BY JSXTRANSFORMER

if (!async.jobs){async.jobs = {};}
if (!async.navigate){async.navigate = {};}
if (!async.pagination){async.pagination = {};}
if (!async.pathindex){async.pathindex = {};}
if (!async.search){async.search = {};}
if (!async.watchfolders){async.watchfolders = {};}
