// JSXTRANSFORMER_SETUP:["/mydmam","/mydmam/async","/mydmam/async/ftpserver","/mydmam/async/jobs","/mydmam/async/navigate","/mydmam/async/pagination","/mydmam/async/pathindex","/mydmam/async/pathindex/metadatas","/mydmam/async/search","/mydmam/async/watchfolders","/mydmam/routes"]
// Copyright (C) hdsdi3g for hd3g.tv 2012-2015
// DO NOT EDIT THIS FILE
// THIS FILE WAS GENERATED AUTOMATICALLY BY JSXTRANSFORMER

if(!mydmam){mydmam = {};}
if(!mydmam.async){mydmam.async = {};}
if(!mydmam.async.ftpserver){mydmam.async.ftpserver = {};}
if(!mydmam.async.jobs){mydmam.async.jobs = {};}
if(!mydmam.async.navigate){mydmam.async.navigate = {};}
if(!mydmam.async.pagination){mydmam.async.pagination = {};}
if(!mydmam.async.pathindex){mydmam.async.pathindex = {};}
if(!mydmam.async.pathindex.metadatas){mydmam.async.pathindex.metadatas = {};}
if(!mydmam.async.search){mydmam.async.search = {};}
if(!mydmam.async.watchfolders){mydmam.async.watchfolders = {};}
if(!mydmam.routes){mydmam.routes = {};}
