// JSXTRANSFORMER_SETUP:{"root":"mydmam","dirs":["async","routes"]}
// DO NOT EDIT THIS FILE
// THIS FILE WAS GENERATED AUTOMATICALLY BY JSXTRANSFORMER

if (!mydmam.async){mydmam.async = {};}
if (!mydmam.routes){mydmam.routes = {};}
